
logo: "https://github.com/Asa-Programming-Language/Asa/blob/main/media/ASA-Full-light.png?raw=true"
logo-dark: "https://github.com/Asa-Programming-Language/Asa/blob/main/media/ASA-Full.png?raw=true"
description: |
  Welcome to the Asa Standard Library documentation. 
  Browse the modules on the left to explore the built-in functions and types that make up the Asa programming language.

github_url: "https://github.com/Asa-Programming-Language/Asa"
